### PR TITLE
Fetch individual record by id

### PR DESCRIPTION
**Pull request by transcental**
Adds a `?recordId` query parameter to fetch the allow listed fields for a given record

### CODE REVIEW

**Review by JosiasAurel — APPROVED** [review]

**Comment by maxwofford** [comment]
Hmmm... this is an interesting idea. I intentionally dropped this after v0 though because I kinda liked making people build their own find requests to keep all the API simple. That said, if you absolutely need it, I have a preference for `router.get("/:base/:tableName/:recordId")` over `router.get("/:base/:tableName") -> req.query.recordId`

**Comment by maxwofford** [comment]
Also, heads up that v0.2 supports this if you want to use that! https://github.com/hackclub/airbridge/blob/master/src/v0.2/README.md#whats-new

**Comment by JosiasAurel** [comment]
misclick

**Comment by transcental** [comment]
v0.2 would probably be better to use, just had a look at it now, ty - will try and figure out how to run it locally and make a PR adding the fields. So far I've not been able to get it to work but I'll get there

**Comment by transcental** [comment]
That would be great, ty! Everything [here](https://github.com/hackclub/airbridge/blob/f7bf9447facd657d654f9be4548b78b6f199a16a/src/v0.1/airtable-info.yml#L107C2-L134C25) is good be exposed publicly

**Pull request closed without merging**
